version: "3"
services:

  django:
    build: ./backend
    command: ["python", "/app/backend/manage.py", "runserver", "0.0.0.0:8090"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"

  front-end:
    build: ./frontend
    command: ["npm", "start"]
    environment:
      - CHOKDIR_USERPOOLING=true
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: